### ISSUE TITLE
Error when running bocadillo create demo

### ISSUE THREAD

**Issue by EricE** [bocadilloproject/bocadillo-cli#10]
Windows 7/64 Python 3.7.3/32

Ran at command prompt in Anaconda environment:
bocadillo create demo

CREATE D:\SVNRepo\projects-sw\async_web\trunk\env\projects\demo\demo
CREATE D:\SVNRepo\projects-sw\async_web\trunk\env\projects\demo\demo\demo
CREATE D:\SVNRepo\projects-sw\async_web\trunk\env\projects\demo\demo\.gitignore
(1071 bytes)
Traceback (most recent call last):
  File "d:\svnrepo\projects-sw\async_web\trunk\env\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\svnrepo\projects-sw\async_web\trunk\env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\SVNRepo\projects-sw\async_web\trunk\env\Scripts\bocadillo.exe\__main__.py", line 9, in <module>
  File "d:\svnrepo\projects-sw\async_web\trunk\env\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "d:\svnrepo\projects-sw\async_web\trunk\env\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "d:\svnrepo\projects-sw\async_web\trunk\env\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\svnrepo\projects-sw\async_web\trunk\env\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\svnrepo\projects-sw\async_web\trunk\env\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "d:\svnrepo\projects-sw\async_web\trunk\env\lib\site-packages\bocadillo_cli\main.py", line 192, in create
    project.create()
  File "d:\svnrepo\projects-sw\async_web\trunk\env\lib\site-packages\bocadillo_cli\main.py", line 126, in create
    self._create_meta()
  File "d:\svnrepo\projects-sw\async_web\trunk\env\lib\site-packages\bocadillo_cli\main.py", line 89, in _create_meta
    [".gitignore", "README.md", "requirements.txt"], root=self.location
  File "d:\svnrepo\projects-sw\async_web\trunk\env\lib\site-packages\bocadillo_cli\main.py", line 81, in _apply_templates
    self._writer.writefile(path, content)
  File "d:\svnrepo\projects-sw\async_web\trunk\env\lib\site-packages\bocadillo_cli\main.py", line 52, in writefile
    f.write(content)
  File "d:\svnrepo\projects-sw\async_web\trunk\env\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 799-800: character maps to <undefined>

Added pdb to main.py at line 52 above f.write(content)

Then:
(Pdb) print(content[790:805])
 Jupyter Notebo

This seems ok?
(Pdb) print(content[799:800])
N

**Comment by florimondmanca** [comment]
Woah, that’s a sneaky one. Thanks for reporting!

I think this could help: https://stackoverflow.com/a/42495690

If so, wanna throw a PR together? 😊

**Comment by EricE** [comment]
My very first PR!  Hopefully I didn't mess it up too badly :)

**Comment by florimondmanca** [comment]
Thanks, will release asap. :-)
